### ISSUE TITLE
While using the :autofocus => true option, validation is too eagerly triggered.

### ISSUE THREAD

**Issue by stevenkolstad** [DavyJonesLocker/client_side_validations-simple_form#19]
The validation is triggered if I click anywhere on the page. In fact, if I click on a link it tries to validate the auto focused field first. Then a second click will work. If I take the autofocus option out, then everything works as expected. What is going on here? Any ideas?

Thanks!!

**Comment by tagliala** [comment]
Hi,

thanks for reporting this.

I'm closing some old issues, hoping that this is not an issue anymore.

If it is still an issue, please provide a reproducible test case and I will consider reopening.

[Contributing guidelines](https://github.com/DavyJonesLocker/client_side_validations-simple_form/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
