### ISSUE TITLE
Force validation

### ISSUE THREAD

**Issue by Linuus** [DavyJonesLocker/client_side_validations-simple_form#24]
I have this issue as described on SO:
http://stackoverflow.com/questions/15062978/force-client-side-validation-of-a-certain-attribute-conditionally

Do you have any solution to this issue?

**Comment by PierreGUI** [comment]
I confirm: it appears giving specific `validate` params to the input won't make it to the generated javascript.
So far, I've been unable to disable validation for a specific field, nor force-enabling (eg conditional validation in model) whether with `validate: true` or `validate: { presence: true }`

Using:
```
client_side_validations-simple_form (3.2.4)
      client_side_validations (~> 4.2.3)
      simple_form (~> 3.2)
```

Thanks

**Comment by tagliala** [comment]
@PierreGUI please provide a reproducible test case in the proper repository (maybe this is related to CSV, so please also try to exclude CSV-simple_form)
