### ISSUE TITLE
Devise

### ISSUE THREAD

**Issue by joao32** [DavyJonesLocker/client_side_validations-simple_form#32]
I can't got it work with Devise. There is any special configuration to get it work with Devise?

**Comment by tagliala** [comment]
Hi,

thanks for reporting this.

I'm using devise + simple_form + csv + csv-simple_form without any trouble.

If it is still an issue, please provide a reproducible test case and I will consider reopening.

[Contributing guidelines](https://github.com/DavyJonesLocker/client_side_validations-simple_form/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
