### ISSUE TITLE
validations are not working in fancybox

### ISSUE THREAD

**Issue by yashwinkumar** [DavyJonesLocker/client_side_validations-simple_form#33]
when i kept `:validate => true` in simple form, it is working perfectly fine without fancybox.

But it is not working in a fancybox. I need to work in a fancybox.

**Comment by tagliala** [comment]
Hi,

thanks for reporting this.

I'm closing some old issues, hoping that this is not an issue anymore.

If it is still an issue, please provide a reproducible test case and I will consider reopening.

[Contributing guidelines](https://github.com/DavyJonesLocker/client_side_validations-simple_form/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
