### ISSUE TITLE
Conditional validation not working

### ISSUE THREAD

**Issue by Lordnibbler** [DavyJonesLocker/client_side_validations-simple_form#34]
I'm passing a `validate: true` to a model with a conditional validator.  The model includes `ActiveModel::Validations` and `ActiveModel::Conversion` and extends `ActiveModel::Naming`.  It does not persist to the database.

The following code, nested inside a `simple_form_for @record, :validate => true, :url => "/some_url" do |f|`

Then, this line does not generate a validator for the field, and no required asterisk shows up:

``` ruby
%td= f.input :problem, validate: true, prompt: "Select a Problem", collection: boombot_problems
```

**Comment by tagliala** [comment]
Hi,

thanks for reporting this.

I'm closing some old issues, hoping that this is not an issue anymore.

If it is still an issue, please provide a reproducible test case and I will consider reopening.

[Contributing guidelines](https://github.com/DavyJonesLocker/client_side_validations-simple_form/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
