### ISSUE TITLE
Doesn't work with some default wrappers

### ISSUE THREAD

**Issue by tagliala** [DavyJonesLocker/client_side_validations-simple_form#38]
DavyJonesLocker/client_side_validations#594

The problem is that apparently `simple_form` moved from `wrappers.bootstrap` to `wrappers.*`

Apparently the default is `:vertical_form` but there are other wrappers

As a temporary workaround, I suggest to add this coffee file to the javascript asset pipeline (please note that your wrapper could be different from `vertical_form`)
```coffee
ClientSideValidations.formBuilders['SimpleForm::FormBuilder'].wrappers.vertical_form =
  add: (element, settings, message) ->
    errorElement = element.parent().find "#{settings.error_tag}.#{settings.error_class}"
    if not errorElement[0]?
      wrapper_tag_element = element.closest(settings.wrapper_tag)
      errorElement = $("<#{settings.error_tag}/>", { class: settings.error_class, text: message })
      wrapper_tag_element.append(errorElement)
    wrapper_class_element = element.closest(".#{settings.wrapper_class}");
    wrapper_class_element.addClass(settings.wrapper_error_class)
    errorElement.text(message)
  remove: (element, settings) ->
    wrapper_class_element = element.closest(".#{settings.wrapper_class}.#{settings.wrapper_error_class}")
    wrapper_tag_element = element.closest(settings.wrapper_tag)
    wrapper_class_element.removeClass(settings.wrapper_error_class)
    errorElement = wrapper_tag_element.find("#{settings.error_tag}.#{settings.error_class}")
    errorElement.remove()
```

Probably this plugin needs some extra love

**Comment by tagliala** [comment]
https://github.com/plataformatec/simple_form/blob/6f2a61015098d43baac67a5f64c5fb4ba9031426/lib/generators/simple_form/templates/config/initializers/simple_form_foundation.rb

https://github.com/plataformatec/simple_form/blob/7abd871b520b24d10d676338801f49004398acd4/lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb

**Comment by adham90** [comment]
thanks :+1:

**Comment by tagliala** [comment]
@adham90 

at least the library should not fail and display an error message in the console like "warning: missing wrapper"

I have some ideas to address this issue

1) Remove the bootstrap wrapper from the base coffeescript and create separate assets for bootstrap and foundation (e.g.: `//= require rails.validations.simple_form.bootstrap`)
2) Keep a single file with all wrappers (default + bootstrap + foundation)

I'm looking for other ideas, I would go for 1

**Comment by tagliala** [comment]
@adham90 and everyone: no thoughts? I should fix this one

**Comment by jhonportella** [comment]
Hi I am using Client-side-validation-simple-form, I follow the instructions but it is not working with bootstrap modal. Any Idea of what can be happening?

**Comment by jhonportella** [comment]
Ohh I have already solved it, I added 

$(document).on 'turbolinks:load', ->
  $('.modal').on 'shown.bs.modal', ->
    $('form[data-validate]').enableClientSideValidations()

to my coffee-script and voila it works.
