### ISSUE TITLE
wrong number of arguments (3 for 2) with Rails 4.0.0, client_side_validations 3.2.5, and simple_form 3.1.0

### ISSUE THREAD

**Issue by ashes999** [DavyJonesLocker/client_side_validations-simple_form#41]
As mentioned on [this client_side_validations issue](https://github.com/DavyJonesLocker/client_side_validations/issues/535#issuecomment-73410223), using this combination of gems results in an error about arguments:

`wrong number of arguments (3 for 2) in app/views/foo/bar.html.erb`

The original (partial) stack reported was:

```
(gem) actionpack-4.0.0.rc1/lib/action_view/helpers/form_helper.rb, line 426
(gem) client_side_validations-3.2.5/lib/client_side_validations/action_view/form_helper.rb, line 25
```

I ran into a similar error yesterday. I can't provide a new stack, since I switched to using a different plugin.

**Comment by tagliala** [comment]
could you please also provide all the info requested here: https://github.com/DavyJonesLocker/client_side_validations-simple_form/blob/master/CONTRIBUTING.md#submitting-a-new-issue?

**Comment by tagliala** [comment]
@ashes999 sorry... you should make sure you are using the last versions from github.

The released gems don't work with Rails >= 4.0

gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations'
gem 'client_side_validations-simple_form', github: 'DavyJonesLocker/client_side_validations-simple_form'

**Comment by ashes999** [comment]
@tagliala As I mentioned in the linked issue, I tried the GitHub version of the gem -- both the main branch and the "rails 4.0 quick fix" brach. Neither worked.

Versions:
- Rails 4.2.0
- Client-side Validation 3.2.5
- client_side_validations-simple_form 2.1.0

I think these are the versions. I don't use this any more, so I don't have any records of my configuration.

Form code from the original issue:

```
<%= simple_form_for(@service) do |f| %>
<%= f.input :name %>
<% end %>
```

I don't have resulting HTML since the form doesn't render.

**Comment by tagliala** [comment]
Client-side Validation 3.2.5
client_side_validations-simple_form 2.1.0

Those versions does not support rails 4.2.0

You must use versions at master branch (4.2.0 and 3.1.0)

Gemfile:
```rb
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations'
gem 'client_side_validations-simple_form', github: 'DavyJonesLocker/client_side_validations-simple_form'
```

**Comment by ashes999** [comment]
Derp...

Like I said, I'm not trying to use this any more, so I don't know exactly what versions I tried.

For details, please see the original issue and ask the original author. I copy/pasted most of his details here, including the stack he provided.

**Comment by tagliala** [comment]
@ashes999 sorry, didn't get it

**Comment by tagliala** [comment]
closing here

**Comment by vijaychouhan-rails** [comment]
tagliala thanks

**Comment by joaorsalmeida** [comment]
Any reason to keep the master branch on Rails 4?

**Comment by tagliala** [comment]
@joaorsalmeida  please do not hijack threads.

Reason is: there is no CSV gem released for rails 5

**Comment by joaorsalmeida** [comment]
@tagliala I'm really sorry about the hijack. I've got lost here between different CSV tabs in my browser :(
