### ISSUE TITLE
Support for Rails 4 and Simple Form 3

### ISSUE THREAD

**Issue by taelton** [DavyJonesLocker/client_side_validations-simple_form#42]
Are there plans to update the dependencies of this gem?

**Comment by tagliala** [comment]
master branch works

**Comment by tagliala** [comment]
ok... it almost works :)

See #38

**Comment by mulvaney** [comment]
any chance of a new release to support Rails 4/Simple form 3?

**Comment by tagliala** [comment]
please keep using the master branches, they work

**Comment by tagliala** [comment]
Done!
