### ISSUE TITLE
DEPRECATION WARNING: input method now accepts a `wrapper_options` argument.

### ISSUE THREAD

**Issue by coorasse** [DavyJonesLocker/client_side_validations-simple_form#45]
from `/lib/client_side_validations/simple_form/form_builder.rb:29`

DEPRECATION WARNING: input method now accepts a `wrapper_options` argument. The method definition without the argument is deprecated and will be removed in the next Simple Form version. Change your code from:
```
    def input
```
to
```
    def input(wrapper_options)
```

**Comment by tagliala** [comment]
as far as I can tell, it's ok on our side because we are overriding this method: https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/form_builder.rb#L110

and its signature is `input(attribute_name, options = {}, &block)`

Let me know if I'm missing something

**Comment by coorasse** [comment]
I missed something, it was one of my own custom inputs the root of the problem, even if the last call on the stack was from client_side_validations

**Comment by tagliala** [comment]
glad you solved
