### ISSUE TITLE
this gem not compatible with - gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations', branch: 'rails5'

### ISSUE THREAD

**Issue by KudosX** [DavyJonesLocker/client_side_validations-simple_form#55]
Get this error when doing bundle update with this gem:
Bundler could not find compatible versions for gem "client_side_validations":
  In Gemfile:
    client_side_validations
    client_side_validations-simple_form was resolved to 1.5.0, which depends on
      client_side_validations (~> 3.2.0)
When i use the standard gem of client_side_validations with rails 5.0.0.rc1 and ruby 2.3.1 it gives me "alias_method_chain is deprecated. Please, use Module#prepend instead." When I went to "gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations', branch: 'rails5' " it fixed my deprecation warning.  But, then isn't compatible with this version of client_side_validations-simple_form. Using Macbook air 10.11.4. with gem 'devise', github: 'plataformatec/devise', branch: 'master'

**Comment by tagliala** [comment]
please use the `rails5` branch on both gems

**Comment by KudosX** [comment]
sorry tagliala, i must have gone brain dead.  so obvious.  thanks so much!! that worked.

**Comment by tagliala** [comment]
don't worry, you're welcome 👍
