### ISSUE TITLE
Simple form + Bootstrap + Rails 5 support not available

### ISSUE THREAD

**Issue by viveksingh1115** [DavyJonesLocker/client_side_validations-simple_form#58]
Hi,
Client side validation not working here I used following gems
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'
gem 'simple_form', '~> 3.2', '>= 3.2.1'
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations', branch: 'rails5'

Please provide the support of Rails 5
If I only used  gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations', branch: 'rails5' but still I got error Cannot read property 'add' of undefined and Cannot read property 'remove' of undefined

**Comment by tagliala** [comment]
you also need 

```rb
gem 'client_side_validations-simple_form', github: 'DavyJonesLocker/client_side_validations-simple_form', branch: 'rails5'
```
