### ISSUE TITLE
Bundling issues with Rails 5.0.0.1

### ISSUE THREAD

**Issue by ycrepeau** [DavyJonesLocker/client_side_validations-simple_form#62]
I have this in my gemfile:

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
...
gem 'simple_form', '~> 3.3.1'
gem 'client_side_validations'
gem 'client_side_validations-simple_form'

I have this error:

client_side_validations (= 4.2.7) was resolved to 4.2.7, which depends on
      rails (< 4.3.0, >= 4.0.0)

Do you have any plan to support 5.0.0 soon?

**Comment by ycrepeau** [comment]
I have found a solution:

http://stackoverflow.com/questions/38962759/client-side-validations-simple-form-in-rails-5

**Comment by tagliala** [comment]
@ycrepeau I can confirm that [Bella's answer](http://stackoverflow.com/a/39656248) is the only approach at the moment. 

Do not expect a gem released soon, sorry
