### ISSUE TITLE
Can not 'bundle install'

### ISSUE THREAD

**Issue by SinghSatyam** [DavyJonesLocker/client_side_validations-simple_form#64]
I am my application from rails 4 to rails 5. As per the ReadMe, the following is the piece required for client_side_validations-simple_form :
```
gem 'rails', '~> 5.1.0'
gem 'simple_form'
gem 'client_side_validations'
gem 'client_side_validations-simple_form', 
    github: 'DavyJonesLocker/client_side_validations-simple_form', 
    branch: 'rails5'
```

But I am getting the following issue: 

```
Bundler could not find compatible versions for gem "client_side_validations":
  In snapshot (Gemfile.lock):
    client_side_validations (= 9.3.1)

  In Gemfile:
    client_side_validations

    client_side_validations-simple_form was resolved to 3.4.0, which depends on
      client_side_validations (~> 5.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

```

**Comment by tagliala** [comment]
Hi,

don't know why you are using an old development branch for csv-simple_form. You should go for

```rb
gem 'rails', '~> 5.1.0'
gem 'simple_form'
gem 'client_side_validations'
gem 'client_side_validations-simple_form'
```

Unfortunately, at the moment I'm writing, this will *not* work because simple_form is not yet compatible with Rails 5.1.0, #1485

Hope it helps

Closing here but feel free to comment

**Comment by tagliala** [comment]
There is also a warning message: https://github.com/DavyJonesLocker/client_side_validations-simple_form/blob/rails5/client_side_validations-simple_form.gemspec#L22
