### ISSUE TITLE
simple_form 4.0 support

### ISSUE THREAD

**Issue by jasonivers** [DavyJonesLocker/client_side_validations-simple_form#66]
There is a new major version of simple_form out (4.0), and the version currently required by this gem (3.5.1) does not support the most recent version of Rails (5.2.0).  Just to test, I forked and changed the requirement to 4.0, and while I don't see any obvious errors (I haven't really had time to do any thorough testing), it no longer seems to have any effect (i.e. there isn't any actual validation).

**Comment by tagliala** [comment]
Let's do it

**Comment by tagliala** [comment]
@jasonivers version 6.6.0 with Simple Form 4.0 released.

All specs are green, including javascript ones.

I've tested it on my application and it works without changing my code

![image](https://user-images.githubusercontent.com/556268/38724545-e3850c30-3f04-11e8-97bb-6353ffc01e14.png)

Let me know if you are experiencing issues

**Comment by jasonivers** [comment]
That seems to have done the trick.  Thank you, especially for the speed with which you handled it.
