### ISSUE TITLE
date_field not validating

### ISSUE THREAD

**Issue by fattaleh** [DavyJonesLocker/client_side_validations-simple_form#67]
Is there a way to get it validate against the new rails date_field?
```
= f.date_field :purchase_date,  validate: { presence: true}
```
id not validating properly

**Comment by tagliala** [comment]
Hi,

sorry for the extremely late reply.

> Is there a way to get it validate against the new rails date_field?

The `date` field is not excluded so it should be automatically supported by CSV

I cannot replicate this issue

![image](https://user-images.githubusercontent.com/556268/45256088-d6318700-b391-11e8-8f5b-47e2297449f2.png)

Rails 5.2
CSV 11.1.3
CSV-SimpleForm 6.6.0
Simple Form 4.0.1
Bootstrap 4 with custom 

Model:
```rb
  validates :birthday, presence: true
```

View:
```erb
    <%= f.input :birthday, as: :date, html5: true, wrapper: :vertical_form %>
```

Also, I think we are on the wrong repository.

If you think there is an issue with client side validations, please report it to https://github.com/DavyJonesLocker/client_side_validations having care of filling **all** the required information
