### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Prabha83** [DavyJonesLocker/client_side_validations-simple_form#71]
I am getting "Cannot read property 'replace' of undefined" in rails.validations.simple_form.js file.

I am using Rails 5.2.1, SImple_form 4.0 and client_side_validations-simple_form-6.6.0.

When I replace bb.use :full_error, wrap_with: { tag: 'div', class: 'invalid-feedback' } with bb.use :error, wrap_with: { tag: 'div', class: 'invalid-feedback' } it works fine.

client_side_validation is not working if full_error method is used to the error message.

**Comment by tagliala** [comment]
@Prabha83 are you using Twitter Bootstrap 4?

**Comment by Prabha83** [comment]
Yes.

**Comment by tagliala** [comment]
Please refer to #65

Workaround: https://github.com/DavyJonesLocker/client_side_validations-simple_form/issues/65#issuecomment-407565848
