### ISSUE TITLE
Cannot read property 'replace' of undefined" without Bootstrap

### ISSUE THREAD

**Issue by no1-knows** [DavyJonesLocker/client_side_validations-simple_form#74]
I have "Cannot read property 'replace' of undefined" when use full_error at simple_form without Bootstrap which is not #65 and #71.

```Ruby
# initializers/simple_form.rb setting like below

# b.use :error, wrap_with: { tag: :span, class: :error }
b.use :full_error, wrap_with: { tag: :span, class: :error }

```
- client_side_validations (16.1.0)
- client_side_validations-simple_form (9.2.0)
- simple_form(5.0.2)
- Rails(6.0.2.1)

The approach is as same as #65?
Rails6 does not support coffee script.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the CSV Community.

I've just provided an issue template here: https://github.com/DavyJonesLocker/client_side_validations-simple_form/issues/new?assignees=&labels=&template=bug_report.md&title= please fill this out
